export const MARK_FLIPPED_CARD = 'MARK_FLIPPED_CARD'
export const MARK_UNFLIPPED_CARDS = 'MARK_UNFLIPPED_CARDS'
export const MARK_COMPLETED_CARDS = 'MARK_COMPLETED_CARDS'
export const RESET_CARDS = 'RESET_CARDS'
