const KEY_CTXT_CARDS = 'CARDS';
const KEY_CTXT_ACTIVE_CARDS = 'ACTIVE_CARDS';
const KEY_CTXT_FOUND_CARDS = 'FOUND_CARDS';
const KEY_CTXT_ALLOWED = 'ALLOWED';
const KEY_CTXT_GAME_FINISHED = 'GAME_FINISHED';

export {
  KEY_CTXT_CARDS,
  KEY_CTXT_ACTIVE_CARDS,
  KEY_CTXT_FOUND_CARDS,
  KEY_CTXT_ALLOWED,
  KEY_CTXT_GAME_FINISHED,
};
